---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable + start the eBPF datapath and session adapter
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - magma-ebpf-gtp.service
    - magma-ebpf-adapter.service
