#!/bin/bash
# =============================================================================
# install-ebpf.sh  —  one-shot, idempotent provisioning of the Magma eBPF GTP-U
# datapath on a Docker AGW.  Add-on to agw_install_ubuntu.sh / the agw_docker role.
#
# After this runs (and on every boot, via systemd) the datapath + session adapter
# come up with NO manual steps; any EXTERNAL gNB or gNB SIMULATOR that attaches a
# UE through the stock Magma AGW components is auto-programmed into eBPF.
#
# It ADDS eBPF; it KEEPS Magma's OVS *userspace* patches (the qfi/tun_id fields that
# pipelined programs and the adapter reads); it DISABLES the eBPF-replaced kernel GTP
# datapath (the gtp0 vport).  It does NOT modify or rebuild any Magma container.
#
#   Usage:  sudo ./install-ebpf.sh [S1U_IFACE]
#           (S1U_IFACE = the gNB/eNB-facing N3/S1-U interface; auto-detected if omitted)
# =============================================================================
set -euo pipefail
SRC_DIR="$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)"   # .../lte/gateway/ebpf
EBPF_DIR=/var/opt/magma/ebpf
BIN_DIR=/usr/local/bin
UNIT_DIR=/etc/systemd/system
ENV_FILE=/etc/magma/ebpf.env
OVS_BR="${OVS_BR:-gtp_br0}"
UE_SUBNET="${UE_SUBNET:-192.168.128.0/24}"
OVS_VETH=gtp_veth0
log(){ echo "[install-ebpf] $*"; }
die(){ echo "[install-ebpf] ERROR: $*" >&2; exit 1; }
[ "$(id -u)" = 0 ] || die "run as root"

# --- 0. detect the S1-U / N3 (gNB-facing) interface ---------------------------
detect_s1u() {
  if [ -n "${1:-}" ]; then echo "$1"; return; fi
  local i
  # Magma's eNB/gNB-facing S1-U interface — enodeb_iface ONLY (nat_iface is the SGi side).
  i=$(grep -sE "^[[:space:]]*enodeb_iface[[:space:]]*:" /etc/magma/pipelined.yml 2>/dev/null | awk '{print $2}' | tr -d '"' | head -1)
  if [ -n "$i" ] && ip link show "$i" >/dev/null 2>&1; then echo "$i"; return; fi
  local defif; defif=$(ip route show default 2>/dev/null | awk '{print $5}' | head -1)
  for i in $(ls /sys/class/net | grep -E '^(eth|ens|enp|eno)'); do
    [ "$i" = "$defif" ] && continue
    echo "$i"; return
  done
  echo eth1
}
S1U_IFACE="$(detect_s1u "${1:-}")"
ip link show "$S1U_IFACE" >/dev/null 2>&1 || die "S1-U iface '$S1U_IFACE' not found"
log "S1-U / N3 (gNB-facing) interface: $S1U_IFACE"

# --- 1. build dependencies ----------------------------------------------------
log "installing build deps..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq || true
apt-get install -y -qq clang llvm gcc make git pkg-config libelf-dev zlib1g-dev \
        "linux-tools-$(uname -r)" 2>/dev/null \
  || apt-get install -y -qq clang llvm gcc make git pkg-config libelf-dev zlib1g-dev linux-tools-generic \
  || log "WARN: some apt packages unavailable; continuing"

# --- 1b. libbpf >= 1.x in /usr/local (focal's apt 0.5 is too old) -------------
if ! ls /usr/local/lib/libbpf.so.1* >/dev/null 2>&1; then
  log "building libbpf 1.3.0 from source..."
  tmp="$(mktemp -d)"
  git clone --depth 1 -b v1.3.0 https://github.com/libbpf/libbpf "$tmp/libbpf" >/dev/null 2>&1 \
    || die "libbpf clone failed (no network?)"
  make -C "$tmp/libbpf/src" -j"$(nproc)" install install_headers PREFIX=/usr/local LIBDIR=/usr/local/lib >/dev/null
  echo /usr/local/lib > /etc/ld.so.conf.d/libbpf.conf; ldconfig
  rm -rf "$tmp"
fi
log "libbpf: $(ls /usr/local/lib/libbpf.so.1* | head -1)"

# --- 1c. a usable bpftool (kernel-bump-safe) ----------------------------------
BPFTOOL="$(command -v bpftool || true)"
if [ -z "$BPFTOOL" ] || ! "$BPFTOOL" version >/dev/null 2>&1; then
  BPFTOOL="$(ls /usr/lib/linux-tools/*/bpftool 2>/dev/null | sort -V | tail -1 || true)"
fi
[ -n "$BPFTOOL" ] && "$BPFTOOL" version >/dev/null 2>&1 || die "no usable bpftool (install linux-tools-$(uname -r))"
log "bpftool: $BPFTOOL"

# --- 2. build eBPF objects + loader, deploy artifacts -------------------------
mkdir -p "$EBPF_DIR"
log "compiling eBPF objects..."
make -C "$SRC_DIR/bpf" >/dev/null || die "bpf build failed"
gcc "$SRC_DIR/src/tc_loader.c" -I/usr/local/include -L/usr/local/lib -lbpf -lelf -lz \
    -o "$EBPF_DIR/tc_loader" || die "tc_loader build failed"
install -m644 "$SRC_DIR/bpf/gtp_decap.o" "$SRC_DIR/bpf/gtp_encap.o" "$SRC_DIR/bpf/gtp_mark.o" "$EBPF_DIR/"
install -m755 "$SRC_DIR/python/ebpf_control.py" "$SRC_DIR/python/ebpf_session_adapter.py" "$EBPF_DIR/"
# point the control plane at the working bpftool
sed -i "s#\"bpftool\"#\"$BPFTOOL\"#g" "$EBPF_DIR/ebpf_control.py"

# --- 3. scripts + env file + systemd units ------------------------------------
install -m755 "$SRC_DIR/deploy/setup-ebpf-gtp.sh" "$SRC_DIR/deploy/teardown-ebpf-gtp.sh" \
              "$SRC_DIR/deploy/install-ebpf-ovs-flows.sh" "$BIN_DIR/"
mkdir -p /etc/magma
cat > "$ENV_FILE" <<EOF
# Magma eBPF GTP-U datapath config — generated by install-ebpf.sh ($(date -u +%FT%TZ 2>/dev/null || echo n/a))
S1U_IF=$S1U_IFACE
OVS_BR=$OVS_BR
OVS_VETH=$OVS_VETH
UE_SUBNET=$UE_SUBNET
ADAPTER_POLL=3
BPFTOOL=$BPFTOOL
EOF
install -m644 "$SRC_DIR/deploy/magma-ebpf-gtp.service" "$SRC_DIR/deploy/magma-ebpf-adapter.service" "$UNIT_DIR/"

# --- 4. disable the eBPF-REPLACED kernel GTP datapath (keep OVS userspace) ----
# eBPF provides GTP encap/decap; the gtp0 vport is not used. Remove it if present.
ovs-vsctl --if-exists del-port "$OVS_BR" gtp0 2>/dev/null || true
# (Intentionally NOT loading any GTP-capable openvswitch DKMS kernel module.)

# --- 5. enable + start (idempotent) -------------------------------------------
systemctl daemon-reload
systemctl enable --now magma-ebpf-gtp.service magma-ebpf-adapter.service

# --- 6. verify ----------------------------------------------------------------
sleep 2
log "--- verification ---"
systemctl is-active magma-ebpf-gtp.service    | sed 's/^/  gtp.service:     /'
systemctl is-active magma-ebpf-adapter.service| sed 's/^/  adapter.service: /'
for d in "$S1U_IFACE" "$OVS_VETH" gtp_veth1; do
  echo "  tc $d ingress: $(tc filter show dev "$d" ingress 2>/dev/null | grep -c bpf) bpf"
done
"$BPFTOOL" map show pinned /sys/fs/bpf/ue_session_map >/dev/null 2>&1 \
  && log "maps pinned OK" || log "WARN: maps not pinned yet"
log "DONE. Datapath is up and persistent. Connect an external gNB / simulator to"
log "the AGW (N3 = $S1U_IFACE); UEs are auto-programmed into eBPF on attach."
